Add meetup 58
devstaff-crete/DevStaff-Heraklion pull request #459
Opened 2020-10-05 18:42 UTC by mzampetakis

2020-10-05 18:46 UTC, DaKnOb requested changes
Please fix these minor changes and then we can merge this.

2020-10-05 18:46 UTC, DaKnOb commented on README.md
> +| #58 | 08/10/2020 | [gRPC: Forget about the REST(https://github.com/devstaff-crete/DevStaff-Heraklion/tree/master/meetups/meetup58-gRPC-Forget-about-the-REST)
Add missing `]`

2020-10-05 18:46 UTC, DaKnOb commented on meetups/meetup58-gRPC-Forget-about-the-REST/README.md
> +# meetup58-gRPC Forget about the REST
Add spacing: `58 - gRPC`.

2020-10-05 18:46 UTC, DaKnOb commented on meetups/meetup58-gRPC-Forget-about-the-REST/README.md
> +# meetup58-gRPC Forget about the REST
Add missing `:`

2020-10-05 19:02 UTC, mzampetakis commented on meetups/meetup58-gRPC-Forget-about-the-REST/README.md
> +# meetup58-gRPC Forget about the REST
Fixed by https://github.com/devstaff-crete/DevStaff-Heraklion/pull/459/commits/c70e63d659e409e05f47d045f214a95dd57593d2

2020-10-05 19:02 UTC, mzampetakis commented on meetups/meetup58-gRPC-Forget-about-the-REST/README.md
> +# meetup58-gRPC Forget about the REST
Fixed by https://github.com/devstaff-crete/DevStaff-Heraklion/pull/459/commits/c70e63d659e409e05f47d045f214a95dd57593d2

2020-10-05 19:03 UTC, mzampetakis commented on README.md
> +| #58 | 08/10/2020 | [gRPC: Forget about the REST(https://github.com/devstaff-crete/DevStaff-Heraklion/tree/master/meetups/meetup58-gRPC-Forget-about-the-REST)
Fixed by https://github.com/devstaff-crete/DevStaff-Heraklion/pull/459/commits/c70e63d659e409e05f47d045f214a95dd57593d2

2020-10-09 18:41 UTC, nickorfas approved these changes

2020-10-09 18:41 UTC, merged